# Auto-generated SSL certificate installer for Windows
# Generated by Loominum

Write-Host "================================================" -ForegroundColor Cyan
Write-Host "Loominum SSL Certificate Installer" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "Error: This script must be run as Administrator" -ForegroundColor Red
    Write-Host ""
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  1. Open PowerShell as Administrator" -ForegroundColor Yellow
    Write-Host "  2. Run: curl.exe -k https://tau:7993/install-cert.ps1 | powershell -Command -" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

# Create temp file for certificate
$tempFile = [System.IO.Path]::GetTempFileName()
$certFile = $tempFile + ".crt"

# Write embedded certificate
@'
-----BEGIN CERTIFICATE-----
MIIFgDCCA2igAwIBAgIUXxCQSsLcqDhhwWPBPebfwgDerhAwDQYJKoZIhvcNAQEL
BQAwDjEMMAoGA1UEAwwDdGF1MB4XDTI2MDIxNTA2NTY1N1oXDTI3MDIxNTA2NTY1
N1owDjEMMAoGA1UEAwwDdGF1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
AgEA77r/WzUI4ShsAQmuQRy5SSO4IG/jnme8DrO3yD7H6DruakUSB9//zUWD3bfg
BdIr2vbYn5Hw0zn7h9GUgKAcYAl5ERA5hgM8zcoUkhxI9LeFH7MuGLLkmBY/c8dr
T9jnDTG/v4KHrGZR7002JviVWbkTR8MivVy/mg66Y+4qQ2V1ekNJcWTBC6zqVmZj
Glyrv6xi5Sd+pN+C2+tAuUo5nctc5rnm1ut1YXcW3HU+yPI8hYP7L71s3hVWs4ta
Go6sv2M7eF26VYQT5mIc79XsZPlT6HdVQ08tMJTGc2aJAs1nNDzrI1wMuDmlRX93
A+ICretD9QuD75kRITHpu2Rx2YDyJjBd7OPqYV96m3v8fVBg2mHScDSQeCzA8F/q
hcYPLtwZs8UE63/0TVUF1HbDG5VqEJsHx9ublrHPdrdkvksDnDo//r4aM1KaC2wu
PDP6N9itYT7YrGU3FhgRzU3r4pIs6f4CJyBstcdDxmoTK4eHXkqzY3AwVd4rzgck
ZrafYU7vu+gxEb7DCzdGQGfZcwvdn+fTB0Av1j7/6udHrXSup8NdQ9kpswQMJD5C
V+O0GuXbbMVwj4lQakmQ0Ox6BHatTrENO1ovhbv7Kem8dbEpOKrtoPCkRjwdOyKa
RnUG9xY2Fs2B6Hobo7agK/niOQnVZYYFg1nqlYHAkTAlcCMCAwEAAaOB1TCB0jAd
BgNVHQ4EFgQUs3pQO8rIROwiNhqGg6dUPIcB5OYwHwYDVR0jBBgwFoAUs3pQO8rI
ROwiNhqGg6dUPIcB5OYwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMC
AaYwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHwYDVR0RBBgwFoIJbG9jYWxob3N0hwR/
AAABggN0YXUwNgYDVR0eAQH/BCwwKqAoMAuCCWxvY2FsaG9zdDAKhwh/AAAB////
/zAFggN0YXUwBoIELnRhdTANBgkqhkiG9w0BAQsFAAOCAgEAySfj8h6nNK8eFYcr
hqUx8P1RcgE8UtUM0iG0f6CFhTV3gUo7u0F3m6sYn2TZRmTABdy7mW/qd6Hdtr9/
GS/mLPR7NIugCqTzjn8il8KGcR/I7auMn2/ZHZKyzcoduFr8BFMWD5NFrghmGPeQ
6Gqvd3DphycuBpGBhtQnEcGiv8iaM20pZKzIWaVpHObE+NvFHNoBX+4OiVBCy9vt
B9UJnHW+cYzzaE6rrbcJko4+r1y0VheLOar6UClgduskKMkfHTvMQK6Mw9lG0BpG
kpekbezna1C4C3Ykh7FnHMHG9bsTTN9l6LGdZ3lbgpSgbr+VKZTrHLu0gBYphSOb
v9XUzwIvV5N8J424ul973Th5TUBk2KmsiaZqvcCr9mNoffMz+L4HawfPJaPZw5bf
MCgD0Bj2RILyEJFoBXtyvFXtqRUPue6Uvml5S3fNF2ypqpI7VI0w8Xpx847XKN97
Z8JWz5MA3OIkvuOdqy7JXd7PZwfXcXf8RIyyDU2L7uMUctQuKa755MeVYqLM+aI0
jk1Y+jTFhqpD5l/pXqDBDfuOUIzjKS26FRgPlDKJgRNMgQJE1q6O7QOUn/IPn3lG
aTHUvJiT01dhUudFDWE/iajkYUjZYs6r+V703qSjgOI9eIUMcb37n8+Yg5o8DIr9
hAd9bnljoqVl6nMqZ3MmULuNp8U=
-----END CERTIFICATE-----
'@ | Set-Content -Path $certFile -Encoding ASCII

Write-Host "Installing certificate to Trusted Root Certification Authorities..." -ForegroundColor Yellow
Write-Host ""
Write-Host "Running: certutil -addstore -f Root $certFile" -ForegroundColor Gray
Write-Host ""

try {
    # Capture certutil output (both stdout and stderr)
    Write-Host "[DEBUG] Calling certutil..." -ForegroundColor Cyan
    $output = & certutil -addstore -f "Root" $certFile 2>&1
    $exitCode = $LASTEXITCODE
    Write-Host "[DEBUG] certutil exit code: $exitCode" -ForegroundColor Cyan
    Write-Host "[DEBUG] Output captured: $($output -ne $null)" -ForegroundColor Cyan
    
    # Show certutil output
    if ($output) {
        Write-Host "[DEBUG] Displaying certutil output:" -ForegroundColor Cyan
        $output | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
        Write-Host ""
    } else {
        Write-Host "[DEBUG] No output from certutil" -ForegroundColor Yellow
    }
    
    Write-Host "[DEBUG] Checking exit code: $exitCode" -ForegroundColor Cyan
    
    if ($exitCode -eq 0) {
        Write-Host ""
        Write-Host "================================================" -ForegroundColor Green
        Write-Host "✓ Certificate installed successfully!" -ForegroundColor Green
        Write-Host "================================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Certificate details:" -ForegroundColor White
        Write-Host "  Subject: CN=tau" -ForegroundColor Gray
        Write-Host "  Issuer:  CN=tau (self-signed)" -ForegroundColor Gray
        Write-Host ""
        Write-Host "The certificate is now trusted by:" -ForegroundColor White
        Write-Host "  - Chrome/Edge/Internet Explorer" -ForegroundColor White
        Write-Host "  - Windows system tools" -ForegroundColor White
        Write-Host ""
        Write-Host "⚠  IMPORTANT: Restart your browser!" -ForegroundColor Yellow
        Write-Host "  1. Close ALL browser windows" -ForegroundColor Yellow
        Write-Host "  2. Kill browser processes: taskkill /F /IM msedge.exe" -ForegroundColor Yellow
        Write-Host "  3. Relaunch and visit: https://tau:7993" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Firefox users: You'll still need to import manually:" -ForegroundColor Yellow
        Write-Host "  1. Download from: https://tau:7993/cert.pem" -ForegroundColor White
        Write-Host "  2. Firefox → about:preferences#privacy → Certificates → View → Authorities → Import" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Host "[DEBUG] certutil failed, throwing exception" -ForegroundColor Red
        throw "certutil exited with code $exitCode"
    }
    
} catch {
    Write-Host ""
    Write-Host "================================================" -ForegroundColor Red
    Write-Host "✗ Certificate installation failed" -ForegroundColor Red
    Write-Host "================================================" -ForegroundColor Red
    Write-Host ""
    Write-Host "Error: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Manual installation:" -ForegroundColor Yellow
    Write-Host "  1. Download: https://tau:7993/cert.pem" -ForegroundColor White
    Write-Host "  2. Double-click the file" -ForegroundColor White
    Write-Host "  3. Click 'Install Certificate'" -ForegroundColor White
    Write-Host "  4. Store Location: Local Machine" -ForegroundColor White
    Write-Host "  5. Place in: Trusted Root Certification Authorities" -ForegroundColor White
    Write-Host ""
    exit 1
} finally {
    # Clean up temp file
    Remove-Item -Path $certFile -ErrorAction SilentlyContinue
    Remove-Item -Path $tempFile -ErrorAction SilentlyContinue
}
