#!/bin/bash
# Auto-generated SSL certificate installer for Linux
# Generated by Snapp executor server

set -e

echo "================================================"
echo "Snapp Executor SSL Certificate Installer"
echo "================================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root (use sudo)"
    echo ""
    echo "Usage:"
    echo "  curl -k https://tau:7993/install-cert.sh | sudo bash"
    exit 1
fi

# Determine cert installation location based on distro
if [ -d /usr/local/share/ca-certificates ]; then
    # Debian/Ubuntu/etc
    CERT_DIR="/usr/local/share/ca-certificates"
    CERT_FILE="$CERT_DIR/snapp-executor.crt"
    UPDATE_CMD="update-ca-certificates"
elif [ -d /etc/pki/ca-trust/source/anchors ]; then
    # RHEL/Fedora/CentOS
    CERT_DIR="/etc/pki/ca-trust/source/anchors"
    CERT_FILE="$CERT_DIR/snapp-executor.pem"
    UPDATE_CMD="update-ca-trust"
else
    echo "Error: Unsupported Linux distribution"
    echo "Please install certificate manually from: https://tau:7993/cert.pem"
    exit 1
fi

echo "Installing certificate to: $CERT_FILE"
echo ""

# Write certificate
cat > "$CERT_FILE" << 'EOF_CERT'
-----BEGIN CERTIFICATE-----
MIIFgDCCA2igAwIBAgIUXxCQSsLcqDhhwWPBPebfwgDerhAwDQYJKoZIhvcNAQEL
BQAwDjEMMAoGA1UEAwwDdGF1MB4XDTI2MDIxNTA2NTY1N1oXDTI3MDIxNTA2NTY1
N1owDjEMMAoGA1UEAwwDdGF1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
AgEA77r/WzUI4ShsAQmuQRy5SSO4IG/jnme8DrO3yD7H6DruakUSB9//zUWD3bfg
BdIr2vbYn5Hw0zn7h9GUgKAcYAl5ERA5hgM8zcoUkhxI9LeFH7MuGLLkmBY/c8dr
T9jnDTG/v4KHrGZR7002JviVWbkTR8MivVy/mg66Y+4qQ2V1ekNJcWTBC6zqVmZj
Glyrv6xi5Sd+pN+C2+tAuUo5nctc5rnm1ut1YXcW3HU+yPI8hYP7L71s3hVWs4ta
Go6sv2M7eF26VYQT5mIc79XsZPlT6HdVQ08tMJTGc2aJAs1nNDzrI1wMuDmlRX93
A+ICretD9QuD75kRITHpu2Rx2YDyJjBd7OPqYV96m3v8fVBg2mHScDSQeCzA8F/q
hcYPLtwZs8UE63/0TVUF1HbDG5VqEJsHx9ublrHPdrdkvksDnDo//r4aM1KaC2wu
PDP6N9itYT7YrGU3FhgRzU3r4pIs6f4CJyBstcdDxmoTK4eHXkqzY3AwVd4rzgck
ZrafYU7vu+gxEb7DCzdGQGfZcwvdn+fTB0Av1j7/6udHrXSup8NdQ9kpswQMJD5C
V+O0GuXbbMVwj4lQakmQ0Ox6BHatTrENO1ovhbv7Kem8dbEpOKrtoPCkRjwdOyKa
RnUG9xY2Fs2B6Hobo7agK/niOQnVZYYFg1nqlYHAkTAlcCMCAwEAAaOB1TCB0jAd
BgNVHQ4EFgQUs3pQO8rIROwiNhqGg6dUPIcB5OYwHwYDVR0jBBgwFoAUs3pQO8rI
ROwiNhqGg6dUPIcB5OYwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMC
AaYwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHwYDVR0RBBgwFoIJbG9jYWxob3N0hwR/
AAABggN0YXUwNgYDVR0eAQH/BCwwKqAoMAuCCWxvY2FsaG9zdDAKhwh/AAAB////
/zAFggN0YXUwBoIELnRhdTANBgkqhkiG9w0BAQsFAAOCAgEAySfj8h6nNK8eFYcr
hqUx8P1RcgE8UtUM0iG0f6CFhTV3gUo7u0F3m6sYn2TZRmTABdy7mW/qd6Hdtr9/
GS/mLPR7NIugCqTzjn8il8KGcR/I7auMn2/ZHZKyzcoduFr8BFMWD5NFrghmGPeQ
6Gqvd3DphycuBpGBhtQnEcGiv8iaM20pZKzIWaVpHObE+NvFHNoBX+4OiVBCy9vt
B9UJnHW+cYzzaE6rrbcJko4+r1y0VheLOar6UClgduskKMkfHTvMQK6Mw9lG0BpG
kpekbezna1C4C3Ykh7FnHMHG9bsTTN9l6LGdZ3lbgpSgbr+VKZTrHLu0gBYphSOb
v9XUzwIvV5N8J424ul973Th5TUBk2KmsiaZqvcCr9mNoffMz+L4HawfPJaPZw5bf
MCgD0Bj2RILyEJFoBXtyvFXtqRUPue6Uvml5S3fNF2ypqpI7VI0w8Xpx847XKN97
Z8JWz5MA3OIkvuOdqy7JXd7PZwfXcXf8RIyyDU2L7uMUctQuKa755MeVYqLM+aI0
jk1Y+jTFhqpD5l/pXqDBDfuOUIzjKS26FRgPlDKJgRNMgQJE1q6O7QOUn/IPn3lG
aTHUvJiT01dhUudFDWE/iajkYUjZYs6r+V703qSjgOI9eIUMcb37n8+Yg5o8DIr9
hAd9bnljoqVl6nMqZ3MmULuNp8U=
-----END CERTIFICATE-----
EOF_CERT

# Update CA certificates
echo "Updating CA certificate store..."
$UPDATE_CMD

echo ""
echo "================================================"
echo "✓ Certificate installed successfully!"
echo "================================================"
echo ""
echo "The certificate is now trusted by:"
echo "  - Chrome/Chromium/Edge"
echo "  - curl, wget, and other system tools"
echo ""
echo "Firefox users: You'll still need to import manually:"
echo "  1. Download: https://tau:7993/cert.pem"
echo "  2. Firefox → about:preferences#privacy → Certificates → View → Authorities → Import"
echo ""
echo "You can now connect to: https://tau:7993"
echo ""
