# Auto-generated SSL certificate installer for Windows
# Generated by UnBilliCord

Write-Host "================================================" -ForegroundColor Cyan
Write-Host "UnBilliCord SSL Certificate Installer" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host "Error: This script must be run as Administrator" -ForegroundColor Red
    Write-Host ""
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  1. Open PowerShell as Administrator" -ForegroundColor Yellow
    Write-Host "  2. Run: curl.exe -k {{CLIENT_URL}}/install-cert.ps1 | powershell -Command -" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

# Create temp file for certificate
$tempFile = [System.IO.Path]::GetTempFileName()
$certFile = $tempFile + ".crt"

# Write embedded certificate
@'
{{CERTIFICATE}}'@ | Set-Content -Path $certFile -Encoding ASCII

Write-Host "Installing certificate to Trusted Root Certification Authorities..." -ForegroundColor Yellow
Write-Host ""
Write-Host "Running: certutil -addstore -f Root $certFile" -ForegroundColor Gray
Write-Host ""

try {
    # Capture certutil output (both stdout and stderr)
    Write-Host "[DEBUG] Calling certutil..." -ForegroundColor Cyan
    $output = & certutil -addstore -f "Root" $certFile 2>&1
    $exitCode = $LASTEXITCODE
    Write-Host "[DEBUG] certutil exit code: $exitCode" -ForegroundColor Cyan
    Write-Host "[DEBUG] Output captured: $($output -ne $null)" -ForegroundColor Cyan
    
    # Show certutil output
    if ($output) {
        Write-Host "[DEBUG] Displaying certutil output:" -ForegroundColor Cyan
        $output | ForEach-Object { Write-Host "  $_" -ForegroundColor Gray }
        Write-Host ""
    } else {
        Write-Host "[DEBUG] No output from certutil" -ForegroundColor Yellow
    }
    
    Write-Host "[DEBUG] Checking exit code: $exitCode" -ForegroundColor Cyan
    
    if ($exitCode -eq 0) {
        Write-Host ""
        Write-Host "================================================" -ForegroundColor Green
        Write-Host "✓ Certificate installed successfully!" -ForegroundColor Green
        Write-Host "================================================" -ForegroundColor Green
        Write-Host ""
        Write-Host "Certificate details:" -ForegroundColor White
        Write-Host "  Subject: CN=tau" -ForegroundColor Gray
        Write-Host "  Issuer:  CN=tau (self-signed)" -ForegroundColor Gray
        Write-Host ""
        Write-Host "The certificate is now trusted by:" -ForegroundColor White
        Write-Host "  - Chrome/Edge/Internet Explorer" -ForegroundColor White
        Write-Host "  - Windows system tools" -ForegroundColor White
        Write-Host ""
        Write-Host "⚠  IMPORTANT: Restart your browser!" -ForegroundColor Yellow
        Write-Host "  1. Close ALL browser windows" -ForegroundColor Yellow
        Write-Host "  2. Kill browser processes: taskkill /F /IM msedge.exe" -ForegroundColor Yellow
        Write-Host "  3. Relaunch and visit: {{CLIENT_URL}}" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Firefox users: You'll still need to import manually:" -ForegroundColor Yellow
        Write-Host "  1. Download from: {{CLIENT_URL}}/cert.pem" -ForegroundColor White
        Write-Host "  2. Firefox → about:preferences#privacy → Certificates → View → Authorities → Import" -ForegroundColor White
        Write-Host ""
    } else {
        Write-Host "[DEBUG] certutil failed, throwing exception" -ForegroundColor Red
        throw "certutil exited with code $exitCode"
    }
    
} catch {
    Write-Host ""
    Write-Host "================================================" -ForegroundColor Red
    Write-Host "✗ Certificate installation failed" -ForegroundColor Red
    Write-Host "================================================" -ForegroundColor Red
    Write-Host ""
    Write-Host "Error: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Manual installation:" -ForegroundColor Yellow
    Write-Host "  1. Download: {{CLIENT_URL}}/cert.pem" -ForegroundColor White
    Write-Host "  2. Double-click the file" -ForegroundColor White
    Write-Host "  3. Click 'Install Certificate'" -ForegroundColor White
    Write-Host "  4. Store Location: Local Machine" -ForegroundColor White
    Write-Host "  5. Place in: Trusted Root Certification Authorities" -ForegroundColor White
    Write-Host ""
    exit 1
} finally {
    # Clean up temp file
    Remove-Item -Path $certFile -ErrorAction SilentlyContinue
    Remove-Item -Path $tempFile -ErrorAction SilentlyContinue
}
