#!/bin/bash
# Auto-generated SSL certificate installer for Linux
# Generated by Loominum

set -e

echo "================================================"
echo "Loominum SSL Certificate Installer"
echo "================================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root (use sudo)"
    echo ""
    echo "Usage:"
    echo "  curl -k {{CLIENT_URL}}/install-cert.sh | sudo bash"
    exit 1
fi

# Determine cert installation location based on distro
if [ -d /usr/local/share/ca-certificates ]; then
    # Debian/Ubuntu/etc
    CERT_DIR="/usr/local/share/ca-certificates"
    CERT_FILE="$CERT_DIR/lum.crt"
    UPDATE_CMD="update-ca-certificates"
elif [ -d /etc/pki/ca-trust/source/anchors ]; then
    # RHEL/Fedora/CentOS
    CERT_DIR="/etc/pki/ca-trust/source/anchors"
    CERT_FILE="$CERT_DIR/lum.pem"
    UPDATE_CMD="update-ca-trust"
else
    echo "Error: Unsupported Linux distribution"
    echo "Please install certificate manually from: {{CLIENT_URL}}/cert.pem"
    exit 1
fi

echo "Installing certificate to: $CERT_FILE"
echo ""

# Write certificate
cat > "$CERT_FILE" << 'EOF_CERT'
{{CERTIFICATE}}EOF_CERT

# Update CA certificates
echo "Updating CA certificate store..."
$UPDATE_CMD

echo ""
echo "================================================"
echo "✓ Certificate installed successfully!"
echo "================================================"
echo ""
echo "The certificate is now trusted by:"
echo "  - Chrome/Chromium/Edge"
echo "  - curl, wget, and other system tools"
echo ""
echo "Firefox users: You'll still need to import manually:"
echo "  1. Download: {{CLIENT_URL}}/cert.pem"
echo "  2. Firefox → about:preferences#privacy → Certificates → View → Authorities → Import"
echo ""
echo "You can now connect to: {{CLIENT_URL}}"
echo ""
